/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.jframe;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
        // configurações inicias do jframe
        setTitle("Cadastramento de Aluno");
        setResizable(false);
        setLocationRelativeTo(null);
        homepage.setSize(683, 384);
        cadpage.setVisible(false);
        visupage.setVisible(false);
        labelrespo.setVisible(false);
        labelrespo1.setVisible(false);
        nomerespons.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conjserie = new javax.swing.ButtonGroup();
        conjcursos = new javax.swing.ButtonGroup();
        homepage = new javax.swing.JPanel();
        aluno = new javax.swing.JLabel();
        título = new javax.swing.JLabel();
        crachá = new javax.swing.JLabel();
        título1 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        cadpage = new javax.swing.JPanel();
        datanasc = new javax.swing.JFormattedTextField();
        labelnome = new javax.swing.JLabel();
        labeldata = new javax.swing.JLabel();
        labelserie = new javax.swing.JLabel();
        labelcurso = new javax.swing.JLabel();
        labelrespo = new javax.swing.JLabel();
        labelrespo1 = new javax.swing.JLabel();
        título2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        nomerespons = new javax.swing.JTextField();
        ti = new javax.swing.JRadioButton();
        eletro = new javax.swing.JRadioButton();
        primeiro = new javax.swing.JRadioButton();
        segundo = new javax.swing.JRadioButton();
        terceiro = new javax.swing.JRadioButton();
        quarto = new javax.swing.JRadioButton();
        barra = new javax.swing.JProgressBar();
        salvar = new javax.swing.JButton();
        fundocad = new javax.swing.JLabel();
        visupage = new javax.swing.JPanel();
        labelnomev = new javax.swing.JLabel();
        labeldatav = new javax.swing.JLabel();
        labelseriev = new javax.swing.JLabel();
        labelcursov = new javax.swing.JLabel();
        labelrespov = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        labelnomev1 = new javax.swing.JLabel();
        labeldatav1 = new javax.swing.JLabel();
        labelcursov1 = new javax.swing.JLabel();
        labelseriev1 = new javax.swing.JLabel();
        labelrespov1 = new javax.swing.JLabel();
        visufundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(2, 35, 28));
        setForeground(new java.awt.Color(0, 0, 0));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(683, 384));
        setResizable(false);

        homepage.setBackground(new java.awt.Color(2, 35, 28));
        homepage.setForeground(new java.awt.Color(141, 165, 115));
        homepage.setMaximumSize(new java.awt.Dimension(683, 384));
        homepage.setMinimumSize(new java.awt.Dimension(683, 384));
        homepage.setName(""); // NOI18N
        homepage.setPreferredSize(new java.awt.Dimension(683, 384));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aluno.png"))); // NOI18N
        homepage.add(aluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, -1, -1));

        título.setFont(título.getFont().deriveFont((título.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 60));
        título.setForeground(new java.awt.Color(34, 182, 202));
        título.setText("Cadastramento ");
        homepage.add(título, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 480, -1));

        crachá.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cracha.png"))); // NOI18N
        homepage.add(crachá, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -20, -1, 130));

        título1.setFont(título1.getFont().deriveFont((título1.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 60));
        título1.setForeground(new java.awt.Color(34, 182, 202));
        título1.setText("do Aluno");
        homepage.add(título1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 410, -1));

        start.setBackground(new java.awt.Color(204, 204, 204));
        start.setForeground(new java.awt.Color(51, 51, 255));
        start.setText("cadastrar");
        start.setToolTipText("");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        homepage.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 200, 50));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        homepage.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 683, 384));

        cadpage.setPreferredSize(new java.awt.Dimension(683, 384));
        cadpage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            datanasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        datanasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanascActionPerformed(evt);
            }
        });
        datanasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datanascKeyPressed(evt);
            }
        });
        cadpage.add(datanasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 80, 30));

        labelnome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelnome.setForeground(new java.awt.Color(255, 255, 255));
        labelnome.setText("Nome: ");
        cadpage.add(labelnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        labeldata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeldata.setForeground(new java.awt.Color(255, 255, 255));
        labeldata.setText("Data de nascimento:");
        cadpage.add(labeldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        labelserie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelserie.setForeground(new java.awt.Color(255, 255, 255));
        labelserie.setText("Série:");
        cadpage.add(labelserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        labelcurso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcurso.setForeground(new java.awt.Color(255, 255, 255));
        labelcurso.setText("Curso:");
        cadpage.add(labelcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        labelrespo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelrespo.setForeground(new java.awt.Color(255, 255, 255));
        labelrespo.setText("respospável:");
        cadpage.add(labelrespo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        labelrespo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelrespo1.setForeground(new java.awt.Color(255, 255, 255));
        labelrespo1.setText("Nome do");
        cadpage.add(labelrespo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        título2.setFont(título2.getFont().deriveFont((título2.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 40));
        título2.setForeground(new java.awt.Color(34, 182, 202));
        título2.setText("Formulário de Cadastro ");
        cadpage.add(título2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 480, -1));

        nome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                nomeComponentAdded(evt);
            }
        });
        nome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeFocusLost(evt);
            }
        });
        nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nomeMouseEntered(evt);
            }
        });
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        nome.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nomePropertyChange(evt);
            }
        });
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeKeyPressed(evt);
            }
        });
        cadpage.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 570, -1));

        nomerespons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeresponsActionPerformed(evt);
            }
        });
        nomerespons.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeresponsKeyPressed(evt);
            }
        });
        cadpage.add(nomerespons, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 250, -1));

        conjserie.add(ti);
        ti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ti.setForeground(new java.awt.Color(255, 255, 255));
        ti.setText("Técnico de Informática");
        ti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiActionPerformed(evt);
            }
        });
        ti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tiKeyPressed(evt);
            }
        });
        cadpage.add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        conjserie.add(eletro);
        eletro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eletro.setForeground(new java.awt.Color(255, 255, 255));
        eletro.setText("Técnico de Eletrotécnica");
        eletro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eletroKeyPressed(evt);
            }
        });
        cadpage.add(eletro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        conjcursos.add(primeiro);
        primeiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        primeiro.setForeground(new java.awt.Color(255, 255, 255));
        primeiro.setText("1º ano do EM");
        primeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                primeiroKeyPressed(evt);
            }
        });
        cadpage.add(primeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        conjcursos.add(segundo);
        segundo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        segundo.setForeground(new java.awt.Color(255, 255, 255));
        segundo.setText("2º ano do EM");
        segundo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                segundoKeyPressed(evt);
            }
        });
        cadpage.add(segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        conjcursos.add(terceiro);
        terceiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        terceiro.setForeground(new java.awt.Color(255, 255, 255));
        terceiro.setText("3º ano do EM");
        terceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceiroActionPerformed(evt);
            }
        });
        terceiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                terceiroKeyPressed(evt);
            }
        });
        cadpage.add(terceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        conjcursos.add(quarto);
        quarto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quarto.setForeground(new java.awt.Color(255, 255, 255));
        quarto.setText("4º ano do ET");
        quarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartoActionPerformed(evt);
            }
        });
        quarto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quartoKeyPressed(evt);
            }
        });
        cadpage.add(quarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, -1, -1));
        cadpage.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 323, 10));

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salvarKeyPressed(evt);
            }
        });
        cadpage.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 140, 30));

        fundocad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fundocad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        fundocad.setMaximumSize(new java.awt.Dimension(683, 384));
        fundocad.setMinimumSize(new java.awt.Dimension(683, 384));
        fundocad.setPreferredSize(new java.awt.Dimension(683, 384));
        cadpage.add(fundocad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        visupage.setPreferredSize(new java.awt.Dimension(683, 384));
        visupage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelnomev.setBackground(new java.awt.Color(255, 255, 255));
        labelnomev.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelnomev.setForeground(new java.awt.Color(34, 182, 202));
        labelnomev.setText("Nome: ");
        visupage.add(labelnomev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        labeldatav.setBackground(new java.awt.Color(255, 255, 255));
        labeldatav.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeldatav.setForeground(new java.awt.Color(34, 182, 202));
        labeldatav.setText("Data de nascimento:");
        visupage.add(labeldatav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        labelseriev.setBackground(new java.awt.Color(255, 255, 255));
        labelseriev.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelseriev.setForeground(new java.awt.Color(34, 182, 202));
        labelseriev.setText("Série:");
        visupage.add(labelseriev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        labelcursov.setBackground(new java.awt.Color(255, 255, 255));
        labelcursov.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcursov.setForeground(new java.awt.Color(34, 182, 202));
        labelcursov.setText("Curso:");
        visupage.add(labelcursov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelrespov.setBackground(new java.awt.Color(255, 255, 255));
        labelrespov.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelrespov.setForeground(new java.awt.Color(34, 182, 202));
        labelrespov.setText("Nome do responsável:");
        visupage.add(labelrespov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        sair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sairKeyPressed(evt);
            }
        });
        visupage.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 303, 110, 30));

        labelnomev1.setBackground(new java.awt.Color(255, 255, 255));
        labelnomev1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelnomev1.setForeground(new java.awt.Color(255, 255, 255));
        labelnomev1.setText("Nome: ");
        visupage.add(labelnomev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 550, -1));

        labeldatav1.setBackground(new java.awt.Color(255, 255, 255));
        labeldatav1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeldatav1.setForeground(new java.awt.Color(255, 255, 255));
        labeldatav1.setText("Data de nascimento:");
        visupage.add(labeldatav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        labelcursov1.setBackground(new java.awt.Color(255, 255, 255));
        labelcursov1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcursov1.setForeground(new java.awt.Color(255, 255, 255));
        labelcursov1.setText("Curso:");
        visupage.add(labelcursov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        labelseriev1.setBackground(new java.awt.Color(255, 255, 255));
        labelseriev1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelseriev1.setForeground(new java.awt.Color(255, 255, 255));
        labelseriev1.setText("Série:");
        visupage.add(labelseriev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        labelrespov1.setBackground(new java.awt.Color(255, 255, 255));
        labelrespov1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelrespov1.setForeground(new java.awt.Color(255, 255, 255));
        labelrespov1.setText("Nome do responsável:");
        visupage.add(labelrespov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        visufundo.setBackground(new java.awt.Color(255, 255, 255));
        visufundo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        visufundo.setForeground(new java.awt.Color(34, 182, 202));
        visufundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        visupage.add(visufundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(cadpage, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
                    .addGap(0, 9, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(visupage, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homepage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cadpage, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(visupage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        cadpage.setVisible(true);
        homepage.setVisible(false);
        nome.requestFocus();
    }//GEN-LAST:event_startActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed

    }//GEN-LAST:event_salvarActionPerformed

    private void nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datanasc.requestFocus();
        }

    }//GEN-LAST:event_nomeKeyPressed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void datanascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datanascActionPerformed

    private void quartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quartoActionPerformed

    private void terceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terceiroActionPerformed

    private void nomeresponsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeresponsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeresponsActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
     
    }//GEN-LAST:event_sairActionPerformed

    private void nomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_nomeComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeComponentAdded

    private void nomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFocusGained

    private void nomePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nomePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nomePropertyChange

    private void nomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomeMouseEntered

    }//GEN-LAST:event_nomeMouseEntered

    private void nomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFocusLost

    private void datanascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datanascKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            // verificando a data
            Date dataNascimento = null;
            SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
            formatoData.setLenient(false);
            String datas = (datanasc.getText());
            try {
                dataNascimento = formatoData.parse(datas);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Inválida!");
            }

            // cálculo da data
            Calendar hoje = Calendar.getInstance();
            hoje.getTime();

            Calendar dataNasc = Calendar.getInstance();
            dataNasc.setTime(dataNascimento);

            int idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);

            if (hoje.get(Calendar.MONTH) < dataNasc.get(Calendar.MONTH)) {
                idade--;
            }

            // cálculo do responsável
            if (idade < 18) {
                labelrespo.setVisible(true);
                labelrespo1.setVisible(true);
                nomerespons.setVisible(true);
                nomerespons.requestFocus();
            } else {
                labelrespo.setVisible(false);
                labelrespo1.setVisible(false);
                nomerespons.setVisible(false);
                ti.requestFocus();
                ti.setSelected(true);
            }
        }
    }//GEN-LAST:event_datanascKeyPressed

    private void tiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiActionPerformed

    private void tiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            primeiro.requestFocus();
            primeiro.setSelected(true);
        }
    }//GEN-LAST:event_tiKeyPressed

    private void nomeresponsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeresponsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ti.requestFocus();
            ti.setSelected(true);
        }
    }//GEN-LAST:event_nomeresponsKeyPressed

    private void eletroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eletroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            primeiro.requestFocus();
            primeiro.setSelected(true);
        }
    }//GEN-LAST:event_eletroKeyPressed

    private void primeiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primeiroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_primeiroKeyPressed

    private void segundoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_segundoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_segundoKeyPressed

    private void terceiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terceiroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_terceiroKeyPressed

    private void quartoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quartoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_quartoKeyPressed

    private void salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salvarKeyPressed
        // mudando o painel
        visupage.setVisible(true);
        cadpage.setVisible(false);

        // tranferindo os dados de um painel para outro
        // nome:
        labelnomev1.setText(nome.getText());

        // curso
        if (ti.isSelected()) {
            labelcursov1.setText(ti.getText());
        } else if (eletro.isSelected()) {
            labelcursov1.setText(eletro.getText());
        }

        //serie
        if (primeiro.isSelected()) {
            labelseriev1.setText(primeiro.getText());
        } else if (segundo.isSelected()) {
            labelseriev1.setText(segundo.getText());
        } else if (terceiro.isSelected()) {
            labelseriev1.setText(terceiro.getText());
        } else if (quarto.isSelected()) {
            labelseriev1.setText(quarto.getText());
        }

        // data dde nascimento
        labeldatav1.setText(datanasc.getText());
        sair.requestFocus();
    }//GEN-LAST:event_salvarKeyPressed

    private void sairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sairKeyPressed
        System.exit(0);
    }//GEN-LAST:event_sairKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aluno;
    private javax.swing.JProgressBar barra;
    private javax.swing.JPanel cadpage;
    private javax.swing.ButtonGroup conjcursos;
    private javax.swing.ButtonGroup conjserie;
    private javax.swing.JLabel crachá;
    private javax.swing.JFormattedTextField datanasc;
    private javax.swing.JRadioButton eletro;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundocad;
    private javax.swing.JPanel homepage;
    private javax.swing.JLabel labelcurso;
    private javax.swing.JLabel labelcursov;
    private javax.swing.JLabel labelcursov1;
    private javax.swing.JLabel labeldata;
    private javax.swing.JLabel labeldatav;
    private javax.swing.JLabel labeldatav1;
    private javax.swing.JLabel labelnome;
    private javax.swing.JLabel labelnomev;
    private javax.swing.JLabel labelnomev1;
    private javax.swing.JLabel labelrespo;
    private javax.swing.JLabel labelrespo1;
    private javax.swing.JLabel labelrespov;
    private javax.swing.JLabel labelrespov1;
    private javax.swing.JLabel labelserie;
    private javax.swing.JLabel labelseriev;
    private javax.swing.JLabel labelseriev1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomerespons;
    private javax.swing.JRadioButton primeiro;
    private javax.swing.JRadioButton quarto;
    private javax.swing.JButton sair;
    private javax.swing.JButton salvar;
    private javax.swing.JRadioButton segundo;
    private javax.swing.JButton start;
    private javax.swing.JRadioButton terceiro;
    private javax.swing.JRadioButton ti;
    private javax.swing.JLabel título;
    private javax.swing.JLabel título1;
    private javax.swing.JLabel título2;
    private javax.swing.JLabel visufundo;
    private javax.swing.JPanel visupage;
    // End of variables declaration//GEN-END:variables
}
