/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author marbi
 */
public class NewJFrame1 extends javax.swing.JFrame {

    private static JTextField getTextFromTextField() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formulario_de_cadastro = new javax.swing.JPanel();
        title_fc = new javax.swing.JLabel();
        textnome = new javax.swing.JLabel();
        textcurso = new javax.swing.JLabel();
        textserie = new javax.swing.JLabel();
        textdatan = new javax.swing.JLabel();
        textcel = new javax.swing.JLabel();
        textemail = new javax.swing.JLabel();
        barra_status = new javax.swing.JProgressBar();
        op_ti = new javax.swing.JCheckBox();
        op_eletro = new javax.swing.JCheckBox();
        op_serie = new javax.swing.JComboBox<>();
        data = new javax.swing.JFormattedTextField();
        celular = new javax.swing.JFormattedTextField();
        cadastrar = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formulario_de_cadastro.setBackground(new java.awt.Color(2, 35, 28));
        formulario_de_cadastro.setForeground(new java.awt.Color(199, 246, 236));
        formulario_de_cadastro.setMaximumSize(new java.awt.Dimension(683, 384));
        formulario_de_cadastro.setMinimumSize(new java.awt.Dimension(683, 384));
        formulario_de_cadastro.setPreferredSize(new java.awt.Dimension(683, 384));

        title_fc.setBackground(new java.awt.Color(255, 255, 255));
        title_fc.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        title_fc.setForeground(new java.awt.Color(199, 246, 236));
        title_fc.setText("Formulário de Cadastro");

        textnome.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textnome.setForeground(new java.awt.Color(199, 246, 236));
        textnome.setText("Nome:");

        textcurso.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textcurso.setForeground(new java.awt.Color(199, 246, 236));
        textcurso.setText("Curso:");

        textserie.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textserie.setForeground(new java.awt.Color(199, 246, 236));
        textserie.setText("Série:");

        textdatan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textdatan.setForeground(new java.awt.Color(199, 246, 236));
        textdatan.setText("Data de Nascimento:");

        textcel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textcel.setForeground(new java.awt.Color(199, 246, 236));
        textcel.setText("Celular:");

        textemail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        textemail.setForeground(new java.awt.Color(199, 246, 236));
        textemail.setText("Email: ");

        barra_status.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                barra_statusStateChanged(evt);
            }
        });

        op_ti.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        op_ti.setForeground(new java.awt.Color(199, 246, 236));
        op_ti.setText("Técnico em Informática");
        op_ti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_tiActionPerformed(evt);
            }
        });

        op_eletro.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        op_eletro.setForeground(new java.awt.Color(199, 246, 236));
        op_eletro.setText("Técnico em Eletrotécnica");
        op_eletro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_eletroActionPerformed(evt);
            }
        });

        op_serie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º ano do EM", "2º ano do EM", "3º ano do EM", "4º ano do CT" }));
        op_serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_serieActionPerformed(evt);
            }
        });

        try {
            data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataActionPerformed(evt);
            }
        });
        data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dataKeyPressed(evt);
            }
        });

        try {
            celular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });
        celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                celularKeyPressed(evt);
            }
        });

        cadastrar.setBackground(new java.awt.Color(110, 209, 188));
        cadastrar.setFont(new java.awt.Font("Source Sans Pro Black", 3, 24)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(2, 35, 28));
        cadastrar.setText("Cadastrar");
        cadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailKeyPressed(evt);
            }
        });

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formulario_de_cadastroLayout = new javax.swing.GroupLayout(formulario_de_cadastro);
        formulario_de_cadastro.setLayout(formulario_de_cadastroLayout);
        formulario_de_cadastroLayout.setHorizontalGroup(
            formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formulario_de_cadastroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formulario_de_cadastroLayout.createSequentialGroup()
                        .addComponent(textdatan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(textcel)
                        .addGap(18, 18, 18)
                        .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formulario_de_cadastroLayout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formulario_de_cadastroLayout.createSequentialGroup()
                                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formulario_de_cadastroLayout.createSequentialGroup()
                                            .addComponent(textemail)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formulario_de_cadastroLayout.createSequentialGroup()
                                            .addComponent(textnome)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(formulario_de_cadastroLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(barra_status, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formulario_de_cadastroLayout.createSequentialGroup()
                                .addComponent(textcurso)
                                .addGap(18, 18, 18)
                                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(op_eletro)
                                    .addGroup(formulario_de_cadastroLayout.createSequentialGroup()
                                        .addComponent(op_ti)
                                        .addGap(101, 101, 101)
                                        .addComponent(textserie)
                                        .addGap(18, 18, 18)
                                        .addComponent(op_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(141, 141, 141))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formulario_de_cadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title_fc, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        formulario_de_cadastroLayout.setVerticalGroup(
            formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formulario_de_cadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title_fc, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnome)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textdatan)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textcel)
                    .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textemail)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(op_ti)
                    .addComponent(textcurso)
                    .addComponent(textserie)
                    .addComponent(op_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(op_eletro)
                .addGap(50, 50, 50)
                .addGroup(formulario_de_cadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formulario_de_cadastroLayout.createSequentialGroup()
                        .addComponent(barra_status, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formulario_de_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formulario_de_cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op_tiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_tiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_tiActionPerformed

    private void op_eletroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_eletroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_op_eletroActionPerformed

    private void op_serieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_serieActionPerformed
                barra_status.setValue(100);
    }//GEN-LAST:event_op_serieActionPerformed

    private void dataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            celular.requestFocus();
        }
    }//GEN-LAST:event_dataKeyPressed

    private void celularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            email.requestFocus();
        }
    }//GEN-LAST:event_celularKeyPressed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
                barra_status.setValue(68);

    }//GEN-LAST:event_emailActionPerformed

    private void emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cadastrar.requestFocus();
        }
    }//GEN-LAST:event_emailKeyPressed

    private void barra_statusStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_barra_statusStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_statusStateChanged

    private void dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataActionPerformed
                barra_status.setValue(35);
    }//GEN-LAST:event_dataActionPerformed

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
                barra_status.setValue(50);
    }//GEN-LAST:event_celularActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        NewJFrame2 frm2 = new NewJFrame2 ();
        this.dispose();
        frm2.setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        
    }//GEN-LAST:event_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra_status;
    private javax.swing.JButton cadastrar;
    private javax.swing.JFormattedTextField celular;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JTextField email;
    private javax.swing.JPanel formulario_de_cadastro;
    private javax.swing.JTextField nome;
    private javax.swing.JCheckBox op_eletro;
    private javax.swing.JComboBox<String> op_serie;
    private javax.swing.JCheckBox op_ti;
    private javax.swing.JLabel textcel;
    private javax.swing.JLabel textcurso;
    private javax.swing.JLabel textdatan;
    private javax.swing.JLabel textemail;
    private javax.swing.JLabel textnome;
    private javax.swing.JLabel textserie;
    private javax.swing.JLabel title_fc;
    // End of variables declaration//GEN-END:variables
}

