/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.jframe;

/**
 *
 * @author aluno
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio = new javax.swing.JPanel();
        icone_aluno = new javax.swing.JLabel();
        título = new javax.swing.JLabel();
        crachá = new javax.swing.JLabel();
        título1 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();
        pgcad = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(2, 35, 28));
        setForeground(new java.awt.Color(0, 0, 0));

        inicio.setBackground(new java.awt.Color(2, 35, 28));
        inicio.setForeground(new java.awt.Color(141, 165, 115));
        inicio.setPreferredSize(new java.awt.Dimension(683, 384));
        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icone_aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aluno.png"))); // NOI18N
        inicio.add(icone_aluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        título.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        título.setForeground(new java.awt.Color(0, 128, 122));
        título.setText("Cadastramento ");
        inicio.add(título, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 480, -1));

        crachá.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cracha.png"))); // NOI18N
        inicio.add(crachá, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 130));

        título1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        título1.setForeground(new java.awt.Color(0, 128, 122));
        título1.setText("do Aluno");
        inicio.add(título1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 410, -1));

        start.setBackground(new java.awt.Color(0, 128, 122));
        start.setFont(new java.awt.Font("Sitka Banner", 1, 36)); // NOI18N
        start.setForeground(new java.awt.Color(0, 255, 204));
        start.setText("start");
        start.setToolTipText("");
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        inicio.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 200, 50));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        inicio.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        pgcad.setBackground(new java.awt.Color(0, 0, 0));
        pgcad.setToolTipText("");
        pgcad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pgcadPropertyChange(evt);
            }
        });
        pgcad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        inicio.add(pgcad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pgcadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pgcadPropertyChange
        
    }//GEN-LAST:event_pgcadPropertyChange

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        
    }//GEN-LAST:event_startMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crachá;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone_aluno;
    private javax.swing.JPanel inicio;
    private javax.swing.JPanel pgcad;
    private javax.swing.JButton start;
    private javax.swing.JLabel título;
    private javax.swing.JLabel título1;
    // End of variables declaration//GEN-END:variables
}
