/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.jframe;

/**
 *
 * @author aluno
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
        pgcad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cursos = new javax.swing.ButtonGroup();
        series = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        inicio = new javax.swing.JPanel();
        icone_aluno = new javax.swing.JLabel();
        título = new javax.swing.JLabel();
        crachá = new javax.swing.JLabel();
        título1 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();
        pgcad = new javax.swing.JPanel();
        varnome = new javax.swing.JTextField();
        teceletro = new javax.swing.JRadioButton();
        tecti = new javax.swing.JRadioButton();
        nome = new javax.swing.JLabel();
        serie = new javax.swing.JLabel();
        curso = new javax.swing.JLabel();
        primeiroano = new javax.swing.JRadioButton();
        segundoano = new javax.swing.JRadioButton();
        terceiroano = new javax.swing.JRadioButton();
        quartoano = new javax.swing.JRadioButton();
        data = new javax.swing.JFormattedTextField();
        datadenascimento = new javax.swing.JLabel();
        nomeresponsa = new javax.swing.JLabel();
        varresponsa = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        fundo1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(2, 35, 28));
        setForeground(new java.awt.Color(0, 0, 0));

        inicio.setBackground(new java.awt.Color(2, 35, 28));
        inicio.setForeground(new java.awt.Color(141, 165, 115));
        inicio.setPreferredSize(new java.awt.Dimension(683, 384));
        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icone_aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aluno.png"))); // NOI18N
        inicio.add(icone_aluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        título.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        título.setForeground(new java.awt.Color(0, 128, 122));
        título.setText("Cadastramento ");
        inicio.add(título, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 480, -1));

        crachá.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cracha.png"))); // NOI18N
        inicio.add(crachá, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 130));

        título1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 60)); // NOI18N
        título1.setForeground(new java.awt.Color(0, 128, 122));
        título1.setText("do Aluno");
        inicio.add(título1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 410, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        inicio.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        pgcad.setBackground(new java.awt.Color(255, 255, 255));
        pgcad.setToolTipText("");
        pgcad.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pgcadPropertyChange(evt);
            }
        });
        pgcad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        varnome.setBackground(new java.awt.Color(255, 255, 255));
        varnome.setForeground(new java.awt.Color(255, 255, 255));
        varnome.setToolTipText("");
        varnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varnomeActionPerformed(evt);
            }
        });
        pgcad.add(varnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 570, 30));

        teceletro.setText("Técnico em Eletrotécnica");
        pgcad.add(teceletro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 190, 30));

        tecti.setText("Técnico em Informática");
        tecti.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tectiItemStateChanged(evt);
            }
        });
        pgcad.add(tecti, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 88, 190, 30));

        nome.setBackground(new java.awt.Color(0, 128, 122));
        nome.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        nome.setForeground(new java.awt.Color(0, 128, 122));
        nome.setText("nome:");
        pgcad.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, 30));

        serie.setBackground(new java.awt.Color(0, 128, 122));
        serie.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        serie.setForeground(new java.awt.Color(0, 128, 122));
        serie.setText("serie:");
        pgcad.add(serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 80, 30));

        curso.setBackground(new java.awt.Color(0, 128, 122));
        curso.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        curso.setForeground(new java.awt.Color(0, 128, 122));
        curso.setText("curso:");
        pgcad.add(curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 40));

        primeiroano.setText("1º ano do EM");
        primeiroano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroanoActionPerformed(evt);
            }
        });
        pgcad.add(primeiroano, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 88, 130, 30));

        segundoano.setText("2º ano do EM");
        segundoano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoanoActionPerformed(evt);
            }
        });
        pgcad.add(segundoano, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 88, 130, 30));

        terceiroano.setText("3º ano do EM");
        terceiroano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terceiroanoActionPerformed(evt);
            }
        });
        pgcad.add(terceiroano, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 128, 130, 30));

        quartoano.setText("4º ano do técnico");
        pgcad.add(quartoano, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 128, 130, 30));

        data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##/##/####"))));
        pgcad.add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 170, 30));

        datadenascimento.setBackground(new java.awt.Color(0, 128, 122));
        datadenascimento.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        datadenascimento.setForeground(new java.awt.Color(0, 128, 122));
        datadenascimento.setText("data de nascimento:");
        pgcad.add(datadenascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, 30));

        nomeresponsa.setBackground(new java.awt.Color(0, 128, 122));
        nomeresponsa.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        nomeresponsa.setForeground(new java.awt.Color(0, 128, 122));
        nomeresponsa.setText("responsavel:");
        pgcad.add(nomeresponsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, 30));

        varresponsa.setBackground(new java.awt.Color(255, 255, 255));
        varresponsa.setForeground(new java.awt.Color(255, 255, 255));
        varresponsa.setToolTipText("");
        varresponsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varresponsaActionPerformed(evt);
            }
        });
        pgcad.add(varresponsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 254, 480, 30));

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        pgcad.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 160, 40));
        pgcad.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 260, -1));

        fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        fundo1.setText("jLabel1");
        pgcad.add(fundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        inicio.add(pgcad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pgcadPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pgcadPropertyChange
        
    }//GEN-LAST:event_pgcadPropertyChange

    private void tectiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tectiItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tectiItemStateChanged

    private void varnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varnomeActionPerformed

    private void primeiroanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeiroanoActionPerformed

    private void segundoanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundoanoActionPerformed

    private void terceiroanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terceiroanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terceiroanoActionPerformed

    private void varresponsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varresponsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varresponsaActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crachá;
    private javax.swing.JLabel curso;
    private javax.swing.ButtonGroup cursos;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JLabel datadenascimento;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundo1;
    private javax.swing.JLabel icone_aluno;
    private javax.swing.JPanel inicio;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel nomeresponsa;
    private javax.swing.JPanel pgcad;
    private javax.swing.JRadioButton primeiroano;
    private javax.swing.JRadioButton quartoano;
    private javax.swing.JButton salvar;
    private javax.swing.JRadioButton segundoano;
    private javax.swing.JLabel serie;
    private javax.swing.ButtonGroup series;
    private javax.swing.JRadioButton teceletro;
    private javax.swing.JRadioButton tecti;
    private javax.swing.JRadioButton terceiroano;
    private javax.swing.JLabel título;
    private javax.swing.JLabel título1;
    private javax.swing.JTextField varnome;
    private javax.swing.JTextField varresponsa;
    // End of variables declaration//GEN-END:variables
}
