/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.jframe;

/**
 *
 * @author aluno
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        título = new javax.swing.JLabel();
        icone_aluno = new javax.swing.JLabel();
        crachá = new javax.swing.JLabel();
        título1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(2, 35, 28));
        setForeground(new java.awt.Color(0, 0, 0));

        painel.setBackground(new java.awt.Color(2, 35, 28));
        painel.setForeground(new java.awt.Color(141, 165, 115));
        painel.setPreferredSize(new java.awt.Dimension(683, 384));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        título.setFont(título.getFont().deriveFont((título.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 60));
        título.setForeground(new java.awt.Color(0, 128, 122));
        título.setText("Cadastramento ");
        painel.add(título, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, -1));

        icone_aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aluna__1_-removebg-preview-removebg-preview.png"))); // NOI18N
        painel.add(icone_aluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 190, -1, 200));

        crachá.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cracha.png"))); // NOI18N
        painel.add(crachá, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 130));

        título1.setFont(título1.getFont().deriveFont((título1.getFont().getStyle() & ~java.awt.Font.ITALIC) | java.awt.Font.BOLD, 60));
        título1.setForeground(new java.awt.Color(0, 128, 122));
        título1.setText("do Aluno");
        painel.add(título1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 410, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setForeground(new java.awt.Color(0, 255, 204));
        jButton1.setText("eree");
        jButton1.setToolTipText("");
        painel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, 50));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        painel.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crachá;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel icone_aluno;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel painel;
    private javax.swing.JLabel título;
    private javax.swing.JLabel título1;
    // End of variables declaration//GEN-END:variables
}
