/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.jframe.ml;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author marbi
 */
public class jframe extends javax.swing.JFrame {

    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
        // configurações inicias do jframe
        setResizable(false);
        setLocationRelativeTo(null);

        // visibilidade dos painéis
        cadpg.setVisible(false);
        visupg.setVisible(false);
        homepg.setVisible(true);

        // visibilidade dos label's
        labelrespo.setVisible(false);
        labelrespo1.setVisible(false);
        nomerespons.setVisible(false);

        start.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conjserie = new javax.swing.ButtonGroup();
        conjcursos = new javax.swing.ButtonGroup();
        homepg = new javax.swing.JPanel();
        título = new javax.swing.JLabel();
        título1 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        alunoestrela = new javax.swing.JLabel();
        cadpg = new javax.swing.JPanel();
        crachá = new javax.swing.JLabel();
        crachá1 = new javax.swing.JLabel();
        título2 = new javax.swing.JLabel();
        título3 = new javax.swing.JLabel();
        datanasc = new javax.swing.JFormattedTextField();
        labelnome = new javax.swing.JLabel();
        labeldata = new javax.swing.JLabel();
        labelserie = new javax.swing.JLabel();
        labelcurso = new javax.swing.JLabel();
        labelrespo = new javax.swing.JLabel();
        labelrespo1 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        nomerespons = new javax.swing.JTextField();
        ti = new javax.swing.JRadioButton();
        eletro = new javax.swing.JRadioButton();
        primeiro = new javax.swing.JRadioButton();
        segundo = new javax.swing.JRadioButton();
        terceiro = new javax.swing.JRadioButton();
        quarto = new javax.swing.JRadioButton();
        salvar = new javax.swing.JButton();
        labeldata1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fundocad = new javax.swing.JLabel();
        visupg = new javax.swing.JPanel();
        aluno = new javax.swing.JLabel();
        labelnomev = new javax.swing.JLabel();
        labeldatav = new javax.swing.JLabel();
        labelseriev = new javax.swing.JLabel();
        labelcursov = new javax.swing.JLabel();
        labelrespov = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        newcad = new javax.swing.JButton();
        labelnomev1 = new javax.swing.JLabel();
        labeldatav1 = new javax.swing.JLabel();
        labelcursov1 = new javax.swing.JLabel();
        labelseriev1 = new javax.swing.JLabel();
        labelrespov1 = new javax.swing.JLabel();
        visufundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(683, 384));
        setMinimumSize(new java.awt.Dimension(683, 384));
        setName("frame"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(683, 384));
        setResizable(false);

        homepg.setMaximumSize(new java.awt.Dimension(683, 384));
        homepg.setMinimumSize(new java.awt.Dimension(683, 384));
        homepg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        título.setFont(new java.awt.Font("Segoe UI Emoji", 1, 60)); // NOI18N
        título.setForeground(new java.awt.Color(204, 204, 255));
        título.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        título.setText("Cadastramento ");
        título.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homepg.add(título, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 530, 80));

        título1.setBackground(new java.awt.Color(0, 51, 51));
        título1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 60)); // NOI18N
        título1.setForeground(new java.awt.Color(204, 204, 255));
        título1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        título1.setText("do Aluno");
        título1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homepg.add(título1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 270, 60));

        start.setBackground(new java.awt.Color(51, 51, 255));
        start.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao.png"))); // NOI18N
        start.setText("CADASTRAR");
        start.setToolTipText("");
        start.setBorder(null);
        start.setContentAreaFilled(false);
        start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        start.setName(""); // NOI18N
        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startMouseExited(evt);
            }
        });
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        homepg.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 280, 80));

        alunoestrela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunoestrela1.png"))); // NOI18N
        homepg.add(alunoestrela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 680, 400));

        cadpg.setMaximumSize(new java.awt.Dimension(683, 384));
        cadpg.setMinimumSize(new java.awt.Dimension(683, 384));
        cadpg.setPreferredSize(new java.awt.Dimension(683, 384));
        cadpg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crachá.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rede.png"))); // NOI18N
        cadpg.add(crachá, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 110, 100));

        crachá1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/rede.png"))); // NOI18N
        cadpg.add(crachá1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 100));

        título2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        título2.setForeground(new java.awt.Color(34, 182, 202));
        título2.setText("de Cadastro");
        cadpg.add(título2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 340, -1));

        título3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        título3.setForeground(new java.awt.Color(34, 182, 202));
        título3.setText("Formulário ");
        cadpg.add(título3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 280, -1));

        try {
            datanasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        datanasc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        datanasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datanascKeyPressed(evt);
            }
        });
        cadpg.add(datanasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 30));

        labelnome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelnome.setForeground(new java.awt.Color(204, 204, 255));
        labelnome.setText("Nome: ");
        cadpg.add(labelnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labeldata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeldata.setForeground(new java.awt.Color(204, 204, 255));
        labeldata.setText("Nascimento:");
        cadpg.add(labeldata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        labelserie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelserie.setForeground(new java.awt.Color(204, 204, 255));
        labelserie.setText("Série:");
        cadpg.add(labelserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        labelcurso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelcurso.setForeground(new java.awt.Color(204, 204, 255));
        labelcurso.setText("Curso:");
        cadpg.add(labelcurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        labelrespo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelrespo.setForeground(new java.awt.Color(204, 204, 255));
        labelrespo.setText("respospável:");
        cadpg.add(labelrespo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 140, 30));

        labelrespo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelrespo1.setForeground(new java.awt.Color(204, 204, 255));
        labelrespo1.setText("Nome do");
        cadpg.add(labelrespo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 110, 20));

        nome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeKeyPressed(evt);
            }
        });
        cadpg.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 590, -1));

        nomerespons.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomerespons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeresponsActionPerformed(evt);
            }
        });
        nomerespons.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeresponsKeyPressed(evt);
            }
        });
        cadpg.add(nomerespons, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 310, -1));

        conjcursos.add(ti);
        ti.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ti.setForeground(new java.awt.Color(204, 204, 255));
        ti.setSelected(true);
        ti.setText("Técnico de Informática");
        ti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tiKeyPressed(evt);
            }
        });
        cadpg.add(ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        conjcursos.add(eletro);
        eletro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eletro.setForeground(new java.awt.Color(204, 204, 255));
        eletro.setText("Técnico de Eletrotécnica");
        eletro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eletroKeyPressed(evt);
            }
        });
        cadpg.add(eletro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        conjserie.add(primeiro);
        primeiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        primeiro.setForeground(new java.awt.Color(204, 204, 255));
        primeiro.setSelected(true);
        primeiro.setText("1º ano do EM");
        primeiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                primeiroKeyPressed(evt);
            }
        });
        cadpg.add(primeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        conjserie.add(segundo);
        segundo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        segundo.setForeground(new java.awt.Color(204, 204, 255));
        segundo.setText("2º ano do EM");
        segundo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                segundoKeyPressed(evt);
            }
        });
        cadpg.add(segundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        conjserie.add(terceiro);
        terceiro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        terceiro.setForeground(new java.awt.Color(204, 204, 255));
        terceiro.setText("3º ano do EM");
        terceiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                terceiroKeyPressed(evt);
            }
        });
        cadpg.add(terceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        conjserie.add(quarto);
        quarto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        quarto.setForeground(new java.awt.Color(204, 204, 255));
        quarto.setText("4º ano do ET");
        quarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quartoActionPerformed(evt);
            }
        });
        quarto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quartoKeyPressed(evt);
            }
        });
        cadpg.add(quarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));

        salvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_1.png"))); // NOI18N
        salvar.setText("SALVAR");
        salvar.setContentAreaFilled(false);
        salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salvarMouseExited(evt);
            }
        });
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        salvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salvarKeyPressed(evt);
            }
        });
        cadpg.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 140, 40));

        labeldata1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeldata1.setForeground(new java.awt.Color(204, 204, 255));
        labeldata1.setText("Data de ");
        cadpg.add(labeldata1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jPanel2.setBackground(new java.awt.Color(70, 9, 126));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(153, 0, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        cadpg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 290, 60));

        jPanel1.setBackground(new java.awt.Color(70, 9, 126));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 0, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        cadpg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 250, 60));

        fundocad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fundocad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunoestrelafundo.png"))); // NOI18N
        fundocad.setMaximumSize(new java.awt.Dimension(683, 384));
        fundocad.setMinimumSize(new java.awt.Dimension(683, 384));
        fundocad.setPreferredSize(new java.awt.Dimension(683, 384));
        cadpg.add(fundocad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 690, 410));

        visupg.setMaximumSize(new java.awt.Dimension(683, 384));
        visupg.setMinimumSize(new java.awt.Dimension(683, 384));
        visupg.setPreferredSize(new java.awt.Dimension(683, 384));
        visupg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aluno.png"))); // NOI18N
        visupg.add(aluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 180, 180));

        labelnomev.setBackground(new java.awt.Color(255, 255, 255));
        labelnomev.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelnomev.setForeground(new java.awt.Color(34, 182, 202));
        labelnomev.setText("Nome: ");
        visupg.add(labelnomev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        labeldatav.setBackground(new java.awt.Color(255, 255, 255));
        labeldatav.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeldatav.setForeground(new java.awt.Color(34, 182, 202));
        labeldatav.setText("Data de nascimento:");
        visupg.add(labeldatav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        labelseriev.setBackground(new java.awt.Color(255, 255, 255));
        labelseriev.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelseriev.setForeground(new java.awt.Color(34, 182, 202));
        labelseriev.setText("Série:");
        visupg.add(labelseriev, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        labelcursov.setBackground(new java.awt.Color(255, 255, 255));
        labelcursov.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelcursov.setForeground(new java.awt.Color(34, 182, 202));
        labelcursov.setText("Curso:");
        visupg.add(labelcursov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        labelrespov.setBackground(new java.awt.Color(255, 255, 255));
        labelrespov.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelrespov.setForeground(new java.awt.Color(34, 182, 202));
        labelrespov.setText("Nome do responsável:");
        visupg.add(labelrespov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_1.png"))); // NOI18N
        sair.setContentAreaFilled(false);
        sair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sair.setLabel("SAIR");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairMouseExited(evt);
            }
        });
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        sair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sairKeyPressed(evt);
            }
        });
        visupg.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 130, 40));

        newcad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botao_1.png"))); // NOI18N
        newcad.setText("NOVO CADASTRO");
        newcad.setContentAreaFilled(false);
        newcad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newcad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newcadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newcadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newcadMouseExited(evt);
            }
        });
        newcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newcadActionPerformed(evt);
            }
        });
        newcad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newcadKeyPressed(evt);
            }
        });
        visupg.add(newcad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 40));

        labelnomev1.setBackground(new java.awt.Color(255, 255, 255));
        labelnomev1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelnomev1.setForeground(new java.awt.Color(255, 255, 255));
        labelnomev1.setText("Nome: ");
        visupg.add(labelnomev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 550, -1));

        labeldatav1.setBackground(new java.awt.Color(255, 255, 255));
        labeldatav1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labeldatav1.setForeground(new java.awt.Color(255, 255, 255));
        labeldatav1.setText("Data de nascimento:");
        visupg.add(labeldatav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        labelcursov1.setBackground(new java.awt.Color(255, 255, 255));
        labelcursov1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelcursov1.setForeground(new java.awt.Color(255, 255, 255));
        labelcursov1.setText("Curso:");
        visupg.add(labelcursov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        labelseriev1.setBackground(new java.awt.Color(255, 255, 255));
        labelseriev1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelseriev1.setForeground(new java.awt.Color(255, 255, 255));
        labelseriev1.setText("Série:");
        visupg.add(labelseriev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        labelrespov1.setBackground(new java.awt.Color(255, 255, 255));
        labelrespov1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelrespov1.setForeground(new java.awt.Color(255, 255, 255));
        labelrespov1.setText("Nome do responsável:");
        visupg.add(labelrespov1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        visufundo.setBackground(new java.awt.Color(255, 255, 255));
        visufundo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        visufundo.setForeground(new java.awt.Color(34, 182, 202));
        visufundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alunoestrelafundo.png"))); // NOI18N
        visupg.add(visufundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homepg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cadpg, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(visupg, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homepg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(cadpg, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(visupg, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
        homepg.setVisible(false);
        cadpg.setVisible(true);
        nome.requestFocus();
    }//GEN-LAST:event_startMouseClicked

    private void startMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseEntered
        Color cor = new Color(153, 255, 255);
        start.setForeground(cor);
    }//GEN-LAST:event_startMouseEntered

    private void startMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseExited
        start.setForeground(UIManager.getColor("Button.foreground"));
    }//GEN-LAST:event_startMouseExited

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        homepg.setVisible(false);
        cadpg.setVisible(true);
        nome.requestFocus();
    }//GEN-LAST:event_startActionPerformed

    private void datanascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datanascKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            // verificando a data
            Date dataNascimento = null;
            SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
            formatoData.setLenient(false);
            String datas = (datanasc.getText());
            try {
                dataNascimento = formatoData.parse(datas);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data Inválida!");
                datanasc.setText("");
            }

            // cálculo da data
            Calendar hoje = Calendar.getInstance();
            hoje.getTime();

            Calendar dataNasc = Calendar.getInstance();
            dataNasc.setTime(dataNascimento);

            int idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);

            if (hoje.get(Calendar.MONTH) < dataNasc.get(Calendar.MONTH)) {
                idade--;
            }

            // cálculo do responsável
            if (idade < 18) {
                labelrespo.setVisible(true);
                labelrespo1.setVisible(true);
                labelrespov.setVisible(true);
                nomerespons.setVisible(true);
                nomerespons.requestFocus();
            } else {
                labelrespo.setVisible(false);
                labelrespov.setVisible(false);
                labelrespo1.setVisible(false);
                nomerespons.setVisible(false);
                ti.requestFocus();
                ti.setSelected(true);
            }
        }
    }//GEN-LAST:event_datanascKeyPressed

    private void nomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeKeyPressed
        // analisando os espaços vazios
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (nome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira seu nome!");
            } else {
                datanasc.requestFocus();
            }
        }
    }//GEN-LAST:event_nomeKeyPressed

    private void nomeresponsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeresponsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeresponsActionPerformed

    private void nomeresponsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeresponsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // analisando os espaços vazios
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (nomerespons.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Insira o nome do seu resposável!");
                } else {
                    ti.requestFocus();
                    ti.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_nomeresponsKeyPressed

    private void tiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            primeiro.requestFocus();
            primeiro.setSelected(true);
        }
    }//GEN-LAST:event_tiKeyPressed

    private void eletroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eletroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            primeiro.requestFocus();
            primeiro.setSelected(true);
        }
    }//GEN-LAST:event_eletroKeyPressed

    private void primeiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primeiroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_primeiroKeyPressed

    private void segundoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_segundoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_segundoKeyPressed

    private void terceiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terceiroKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_terceiroKeyPressed

    private void quartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quartoActionPerformed

    private void quartoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quartoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            salvar.requestFocus();
        }
    }//GEN-LAST:event_quartoKeyPressed

    private void salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseClicked
        // mudando o painel e tranferindo os dados de um painel para outro
        // nome:
        if (nome.getText().isEmpty() || datanasc.getText().isEmpty() || labelrespo.isVisible() && nomerespons.getText().isEmpty()) {
            if (nomerespons.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira o nome do seu responsável!");
                nomerespons.requestFocus();
            }
            if (datanasc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira sua data de nascimento!");
                datanasc.requestFocus();
            }
            if (nome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira seu nome!");
                nome.requestFocus();
            }
        } else {
            labelnomev1.setText(nome.getText());
            labeldatav1.setText(datanasc.getText());
            labelrespov1.setText(nomerespons.getText());
            visupg.setVisible(true);
            cadpg.setVisible(false);
        }
        // curso
        if (ti.isSelected()) {
            labelcursov1.setText(ti.getText());
        } else if (eletro.isSelected()) {
            labelcursov1.setText(eletro.getText());
        }

        //serie
        if (primeiro.isSelected()) {
            labelseriev1.setText(primeiro.getText());
        } else if (segundo.isSelected()) {
            labelseriev1.setText(segundo.getText());
        } else if (terceiro.isSelected()) {
            labelseriev1.setText(terceiro.getText());
        } else if (quarto.isSelected()) {
            labelseriev1.setText(quarto.getText());
        }
    }//GEN-LAST:event_salvarMouseClicked

    private void salvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseEntered
        Color cor = new Color(153, 255, 255);
        salvar.setForeground(cor);
    }//GEN-LAST:event_salvarMouseEntered

    private void salvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMouseExited
        salvar.setForeground(UIManager.getColor("Button.foreground"));
    }//GEN-LAST:event_salvarMouseExited

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salvarActionPerformed

    private void salvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salvarKeyPressed
        // mudando o painel e tranferindo os dados de um painel para outro
        // nome:
        if (nome.getText().isEmpty() || datanasc.getText().isEmpty() || labelrespo.isVisible() && nomerespons.getText().isEmpty()) {
            if (nomerespons.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira o nome do seu responsável!");
                nomerespons.requestFocus();
            }
            if (datanasc.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira sua data de nascimento!");
                datanasc.requestFocus();
            }
            if (nome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Insira seu nome!");
                nome.requestFocus();
            }
        } else {
            labelnomev1.setText(nome.getText());
            labeldatav1.setText(datanasc.getText());
            labelrespov1.setText(nomerespons.getText());
            visupg.setVisible(true);
            cadpg.setVisible(false);
        }
        // curso
        if (ti.isSelected()) {
            labelcursov1.setText(ti.getText());
        } else if (eletro.isSelected()) {
            labelcursov1.setText(eletro.getText());
        }

        //serie
        if (primeiro.isSelected()) {
            labelseriev1.setText(primeiro.getText());
        } else if (segundo.isSelected()) {
            labelseriev1.setText(segundo.getText());
        } else if (terceiro.isSelected()) {
            labelseriev1.setText(terceiro.getText());
        } else if (quarto.isSelected()) {
            labelseriev1.setText(quarto.getText());
        }
    }//GEN-LAST:event_salvarKeyPressed

    private void sairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sairKeyPressed
        System.exit(0);
    }//GEN-LAST:event_sairKeyPressed

    private void newcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newcadActionPerformed
        visupg.setVisible(false);
        cadpg.setVisible(true);
        nome.setText("");
        datanasc.setText("");
        nomerespons.setText("");
        nome.requestFocus();
        labelrespo.setVisible(false);
        labelrespo1.setVisible(false);
        nomerespons.setVisible(false);
    }//GEN-LAST:event_newcadActionPerformed

    private void newcadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newcadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            visupg.setVisible(false);
            cadpg.setVisible(true);
            nome.setText("");
            datanasc.setText("");
            nomerespons.setText("");
            nome.requestFocus();
            labelrespo.setVisible(false);
            labelrespo1.setVisible(false);
            nomerespons.setVisible(false);
        }
    }//GEN-LAST:event_newcadKeyPressed

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Obrigado por utilizar o programa! Te vejo na próxima.");
        System.exit(0);
    }//GEN-LAST:event_sairMouseClicked

    private void newcadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcadMouseClicked
        visupg.setVisible(false);
        cadpg.setVisible(true);
        nome.setText("");
        datanasc.setText("");
        nomerespons.setText("");
        nome.requestFocus();
        labelrespo.setVisible(false);
        labelrespo1.setVisible(false);
    }//GEN-LAST:event_newcadMouseClicked

    private void newcadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcadMouseEntered
        Color cor = new Color(153, 255, 255);
        newcad.setForeground(cor);
    }//GEN-LAST:event_newcadMouseEntered

    private void sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseEntered
        Color cor = new Color(153, 255, 255);
        sair.setForeground(cor);
    }//GEN-LAST:event_sairMouseEntered

    private void newcadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newcadMouseExited
       newcad.setForeground(UIManager.getColor("Button.foreground"));
    }//GEN-LAST:event_newcadMouseExited

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sairActionPerformed

    private void sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseExited
        sair.setForeground(UIManager.getColor("Button.foreground"));
    }//GEN-LAST:event_sairMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aluno;
    private javax.swing.JLabel alunoestrela;
    private javax.swing.JPanel cadpg;
    private javax.swing.ButtonGroup conjcursos;
    private javax.swing.ButtonGroup conjserie;
    private javax.swing.JLabel crachá;
    private javax.swing.JLabel crachá1;
    private javax.swing.JFormattedTextField datanasc;
    private javax.swing.JRadioButton eletro;
    private javax.swing.JLabel fundocad;
    private javax.swing.JPanel homepg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelcurso;
    private javax.swing.JLabel labelcursov;
    private javax.swing.JLabel labelcursov1;
    private javax.swing.JLabel labeldata;
    private javax.swing.JLabel labeldata1;
    private javax.swing.JLabel labeldatav;
    private javax.swing.JLabel labeldatav1;
    private javax.swing.JLabel labelnome;
    private javax.swing.JLabel labelnomev;
    private javax.swing.JLabel labelnomev1;
    private javax.swing.JLabel labelrespo;
    private javax.swing.JLabel labelrespo1;
    private javax.swing.JLabel labelrespov;
    private javax.swing.JLabel labelrespov1;
    private javax.swing.JLabel labelserie;
    private javax.swing.JLabel labelseriev;
    private javax.swing.JLabel labelseriev1;
    private javax.swing.JButton newcad;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomerespons;
    private javax.swing.JRadioButton primeiro;
    private javax.swing.JRadioButton quarto;
    private javax.swing.JButton sair;
    private javax.swing.JButton salvar;
    private javax.swing.JRadioButton segundo;
    private javax.swing.JButton start;
    private javax.swing.JRadioButton terceiro;
    private javax.swing.JRadioButton ti;
    private javax.swing.JLabel título;
    private javax.swing.JLabel título1;
    private javax.swing.JLabel título2;
    private javax.swing.JLabel título3;
    private javax.swing.JLabel visufundo;
    private javax.swing.JPanel visupg;
    // End of variables declaration//GEN-END:variables
}
